
name: Build and deploy ASP.Net Core app to an Azure Web App

env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '5'                 # set this to the .NET Core version to use
  
on:
  #create:
  #  branches:
  #    - 'releases/**'
  #push:
  #  branches: [ "main" ]
  #workflow_dispatch:
  workflow_call:
    

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setting Branch Name to Variable
        run: |        
         echo "DC_WEB_NAME=${{env.PROJECT_NAME}}-${{ github.ref_name }}-dev-web" >> $GITHUB_ENV

      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Publish
        run: dotnet publish MoneyBall/MoneyBall.csproj -c Release -o website
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: website
          path: MoneyBall/website/**
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: website
          path: website
      
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy web app
        id: deploywebapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.DC_WEB_NAME }}
          package: website
      
      - name: az cli logout
        run: az logout