name: Branching-create-iac
on:
   create:
     branches:
      - 'releases/**'
env:
  PROJECT_NAME: 'MoneyBall'
jobs:
   Run_IAC_for_new_branch:
      name: 'Running IAC for new Branch'
      runs-on: ubuntu-latest
      # if: ${{contains(github.ref, 'refs/heads/releases/')}}
      steps:
         - name: Setting Branch Name to Variable
           run: |
            #echo "BRANCH_NAME=$(echo $GITHUB_REF | cut -d'/' -f 4)" >> $GITHUB_ENV
            echo "DC_ENV_NAME=${{env.PROJECT_NAME}}-${{ github.ref_name }}-dev" >> $GITHUB_ENV
            echo "DC_WEB_NAME=${{ENV.DC_ENV_NAME}}-web" >> $GITHUB_ENV
            echo "RG_NAME=${{ env.PROJECT_NAME }}-${{ env.DC_ENV_Name }}" >> $GITHUB_ENV
                 
         - uses: azure/login@v1
           with:
              creds: ${{ secrets.AZURE_CREDENTIALS }}
              enable-AzPSSession: true

         - name: Create Project Environment  for new branch which will allow environments to be built against
           uses: azure/powershell@v1
           with:
             azPSVersion: "3.1.0"
             inlineScript: |
              az devcenter dev environment create `
              --dev-center-name devcenter-test `
              --project-name '${{ env.PROJECT_NAME }}' `
              --environment-name '${{ env.DC_ENV_NAME }}' `
              --environment-type 'Development' `
              --environment-definition-name Ilitch_Demo `
              --catalog-name Ilitch_Demo `
              --parameters "{'name': '${{ env.DC_ENV_NAME }}'}"         
            
   Deploy_to_new_environment:
      needs: Run_IAC_for_new_branch
      uses: ./.github/workflows/azure-webapps-dotnet-core.yml
      

              
              
         
               
               
