name: Branching-create-iac
on:
   create
jobs:
   Run_IAC_for_new_branch:
      name: 'Running IAC for new Branch'
      runs-on: ubuntu-latest
      if: ${{contains(github.ref, 'refs/heads/releases/')}}
      steps:
         - name: Setting Branch Name to Variable
           run: |
            # Short name for current branch. For PRs, use target branch (base ref)
            echo "BRANCH_NAME=$(echo $GITHUB_REF | cut -d'/' -f 4)" >> $GITHUB_ENV
            echo "PROJECT_NAME=$(MoneyBall-$BRANCH_NAME") >> $GITHUB_ENV
         
         - name: 'Setting IAC for new branch'
           run: |
            echo ${{ env.BRANCH_NAME }}
         - uses: azure/login@v1
           with:
              creds: ${{ secrets.AZURE_CREDENTIALS }}
              enable-AzPSSession: true

         - name: Install ADE extension
           uses: azure/powershell@v1
           with:
             azPSVersion: "3.1.0"
             inlineScript: |
               az extension add --name devcenter --upgrade
         
         - name: Create Project Environment  for new branch which will allow environments to be built against
           uses: azure/powershell@v1
           with:
             azPSVersion: "3.1.0"
             inlineScript: |
              az devcenter dev environment create `
              --dev-center-name devcenter-test `
              --project-name '${{ env.PROJECT_NAME }}' `
              --environment-name '${{ env.PROJECT_NAME }}-dev' `
              --environment-type 'Development' `
              --environment-definition-name Ilitch_Demo `
              --catalog-name Ilitch_Demo `
              --parameters "{'name': '${{ env.PROJECT_NAME }}-dev'}"             

              
              
         
               
               
